DROP TABLE IF EXISTS cpus;
DROP TABLE IF EXISTS keyboards;
DROP TABLE IF EXISTS memories;
DROP TABLE IF EXISTS screen_resolutions;
DROP TABLE IF EXISTS gpus;
DROP TABLE IF EXISTS laptops;
DROP TABLE IF EXISTS screens;
DROP TABLE IF EXISTS storages;